# @package _global_
# LSTM Architecture for EMG-to-Keystroke Prediction

module:
  _target_: emg2qwerty.lightning.LSTMCTCModule
  in_features: 1056  # freq * bands * channels = (64 // 2 + 1) * 2 * 16
  hidden_size: 256
  num_layers: 2
  dropout: 0.3

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding: [1800, 200]

